# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname interaction-effect-pps
#' @description `cxx_inter_pps`.
#' @noRd
cxx_inter_pps <- function(W, r, x) {
    .Call(`_PPSFS_cxx_inter_pps`, W, r, x)
}

